version: "3.9"
services:
# nginx
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./project:/var/www/html
    depends_on:
      - php-fpm_8.2
# php
  php-fpm_8.2:
    container_name: php-fpm_8.2
    hostname: php-fpm_8.2
    image: php:8.2.0-fpm-bullseye
    build:
      context: .
      dockerfile: docker/php-fpm_8.2/Dockerfile
    networks:
      - app
    restart: unless-stopped
    volumes:
      - ./project:/var/www/html
# postgres
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    networks:
      - app
    ports:
      - "5432:5432"
    restart: always

    environment:
      POSTGRES_USER: project
      POSTGRES_PASSWORD: project
      POSTGRES_DB: project

networks:
  app:
    driver: bridge
